# Generated by Django 4.2.3 on 2023-07-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('idade', models.IntegerField()),
                ('altura', models.FloatField()),
                ('local_de_origem', models.CharField(default='', max_length=20)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
